#!/bin/bash -e

# Copyright (c) 2014 Michal Srb
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
#
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
#
# 3. This notice may not be removed or altered from any source
#    distribution.

specfile="*.spec"
bumpminor=
chlogmessage="Rebuilt"

function usage {
    echo "Usage: "`basename "$0"`" [-r] [-h] [-f specfile] [changelog message]"
}

while [[ $# -ne 0 ]]; do

    case "$1" in
        "-f")
            if [[ $# -ge 2 ]]; then
                specfile="$2"
                shift 2
                continue
            fi
            echo "-f: missing argument" 1>&2
            usage
            exit 1
            ;;
        "-r")
            bumpminor=yes
            shift
            ;;
        "-h")
            usage
            exit 0
            ;;
        *)
            if [[ $# -eq 1 ]]; then
                chlogmessage="$1"
                shift
                continue
            fi
            echo "Unknown parameter: $1" 1>&2
            usage
            exit 1
    esac
done


if [ ! -f ${specfile} ]; then
    echo "$specfile: no such file" 1>&2
    exit 1
fi

username=`git config --get user.name`
email=`git config --get user.email`


version=`rpmspec -P ${specfile} | sed -n 's/\s*Version:\s*\(.*\)$/\1/p'`

currentrel=`sed -n 's/^Release:\s*\([0-9.]\+\)[a-ZA-Z%]*.*/\1/p' ${specfile}`

trailingdot=
minoradded=
if [[ $currentrel == *\. ]]; then
    currentrel=${currentrel%.}
    trailingdot=yes
fi

# extract major release number
major=`echo ${currentrel} | sed -n 's/^\([0-9]\+\).*/\1/p'`
# extract minor release number (if any)
minor=`echo ${currentrel} | sed -n 's/.*\.\([0-9]\+\)$/\1/p'`

nextmajor=$major
nextminor=$minor

if [[ -z $bumpminor ]]; then
    # bump major
    if [[ "$major" -ne 0 || -z $minor ]]; then
        nextmajor=$((major + 1))
    else
        # it's probably a pre-release package, so release number
        # looks something like "0.1-%{?dist}"
        # bump minor release number
        nextminor=$((minor + 1))
    fi
else
    # bump minor
    if [[ -n $minor ]]; then
        nextminor=$((minor + 1))
    else
        nextminor=".1"
        minoradded=yes
    fi
fi

newrel="${nextmajor}${currentrel#$major}"

if [[ -z $minoradded ]]; then
    newrel="${newrel%$minor}${nextminor}"
else
    newrel="${newrel}${nextminor}"
fi

if [[ -n $trailingdot ]]; then
    newrel="$newrel."
fi

# bump release
sed -i "s/^\(Release:\s*\)\([0-9.]\+\)\([a-ZA-Z%]*.*\)/\1$newrel\3/" ${specfile}

fullrel=`rpmspec -P ${specfile} | sed -n 's/\s*Release:\s*\(.*\)\..*$/\1/p'`

logheader="* `date +'%a %b %d %Y'` $username <$email> - $version-$fullrel"

# add changelog entry
sed -i "/^%changelog/ a\\$logheader\n- $chlogmessage\n" ${specfile}

